version: "3"
services:
  ctop:
    # docker run -d --name ctop --restart=always -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest
    name: ctop
    image: quay.io/vektorlab/ctop:latest
    restart: always
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  portainer:
    # docker run -d --name portainer --restart=always -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock --restart on-failure portainer/portainer --logo "https://raw.githubusercontent.com/multinodeio/files/master/mn-portainer-logo.png" --templates https://raw.githubusercontent.com/multinodeio/files/master/templates.json --admin-password '$2y$05$65FBj8ILqYCOsJ.X.xZo1ufoemxMDXnk/xDW4ZBnU1VawImKvadGO'
    name: portainer
    image: portainer/portainer
    privileged: true
    restart: always
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/local/portainer:/root/data
    command: "-d /root/data --logo 'https://multinode.io/s/mn-portainer-logo.png' --templates 'https://raw.githubusercontent.com/multinodeio/files/master/templates.json' --admin-password '$2y$05$65FBj8ILqYCOsJ.X.xZo1ufoemxMDXnk/xDW4ZBnU1VawImKvadGO'"
    ports: 
      - 9000:9000