version: "3"
services:
  ctop:
    image: quay.io/vektorlab/ctop:latest
    restart: always
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  portainer:
    image: portainer/portainer
    privileged: true
    restart: always
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/local/portainer:/root/data
    command: "-H unix:///var/run/docker.sock -d /root/data --logo 'https://multinode.io/s/mn-portainer-logo.png' --templates 'https://raw.githubusercontent.com/multinodeio/files/master/templates.json' --admin-password '$$2y$$05$$65FBj8ILqYCOsJ.X.xZo1ufoemxMDXnk/xDW4ZBnU1VawImKvadGO'"
    ports: 
      - 9000:9000
  watchtower:
    image: v2tec/watchtower
    privileged: true
    restart: always
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock